apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: amokscience/hello
    newTag: staging-540c21ede7e2d8501b39634aff1444bfe55b190b

patches:
  - target:
      kind: Deployment
      name: staging-hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
