apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: amokscience/hello
    newTag: staging-c09e40fbe3df8bc2297e038a1ac8fa81f3ef02fe

patches:
  - target:
      kind: Deployment
      name: staging-hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
