apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: amokscience/hello
    newTag: staging-b75cc5fb51c8613980dfeb7dbc77389888a1b57d

patches:
  - target:
      kind: Deployment
      name: staging-hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
