apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/hello
    targetRevision: HEAD
    path: kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/hello
    targetRevision: HEAD
    path: kustomize/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/hello
    targetRevision: HEAD
    path: kustomize/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/hello
    targetRevision: HEAD
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
