apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

bases:
  - ../../base

namePrefix: qa-

commonLabels:
  environment: qa

images:
  - name: amokscience/hello
    newTag: qa-d15f54d416f0760d7e4130900e68cd89098cf81d

patches:
  - target:
      kind: Deployment
      name: qa-hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
