apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

bases:
  - ../../base

namePrefix: qa-

commonLabels:
  environment: qa

images:
  - name: amokscience/hello
    newTag: qa-7cd3d9e756ee2450a3fc87fb7ef2fa899e0771ac

configMapGenerator:
  - name: hello-config
    literals:
      - environment=qa
      - hello=Hello from qa Kubernetes!

patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
