apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

images:
  - name: amokscience/hello
    newTag: prod-513a0ca493d148186d6dd9f3b613c92de840f552

patches:
  - target:
      kind: Deployment
      name: prod-hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
