apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

images:
  - name: amokscience/hello
    newTag: prod-22f66c71aa63d31b6415661027b0d02aa1d62919

patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
