apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

images:
  - name: amokscience/hello
    newTag: prod-8bcc160ac1c22634a427682ceac23eca4b5ad2f6

configMapGenerator:
  - name: hello-config
    literals:
      - environment=prod
      - hello=Hello from prod Kubernetes!

patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
