apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

images:
  - name: amokscience/hello
    newTag: dev-5b84e25a3ca020413a3875dfd83496f5d3ee8263

configMapGenerator:
  - name: hello-config
    literals:
      - environment=dev
      - hello=Hello from dev Kubernetes!

patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
