apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

images:
  - name: amokscience/hello
    newTag: dev-2268b89dc28397de9e3c1d1d6e3d1e22fd28aa2e

configMapGenerator:
  - name: hello-config
    literals:
      - environment=dev
      - hello=Hello from dev Kubernetes!

patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
