apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

images:
  - name: amokscience/hello
    newTag: dev-a3293bb9c812402b8dd3a5aced5aa2cca3190f7a

patches:
  - target:
      kind: Deployment
      name: dev-hello-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
